name: Full Stack CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore API
      run: dotnet restore ToDoApi/ToDoApi.csproj

    - name: Restore Blazor
      run: dotnet restore ToDoBlazorApp/ToDoBlazorApp.csproj

    - name: Build API
      run: dotnet build ToDoApi/ToDoApi.csproj -c Release --no-restore

    - name: Build Blazor
      run: dotnet build ToDoBlazorApp/ToDoBlazorApp.csproj -c Release --no-restore

    - name: Publish API
      run: dotnet publish ToDoApi/ToDoApi.csproj -c Release -o publish-api

    - name: Publish Blazor
      run: dotnet publish ToDoBlazorApp/ToDoBlazorApp.csproj -c Release -o publish-blazor
